# Generated by Django 2.2.5 on 2019-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attechment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('filepath', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'attechment',
                'verbose_name_plural': 'attechments',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('filepath', models.CharField(max_length=256)),
                ('school', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'get_latest_by': 'id',
            },
        ),
    ]
