# Generated by Django 2.2.5 on 2019-10-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'chat_block',
                'verbose_name_plural': 'chat_blocks',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.IntegerField()),
                ('user_2', models.IntegerField()),
                ('latest_time', models.DateTimeField()),
                ('latest_sender', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('importance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'chats',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('content', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'get_latest_by': 'id',
            },
        ),
    ]
