# Generated by Django 2.2.5 on 2019-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('creator', models.IntegerField()),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SchoolApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('school_id', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('apply_time', models.DateTimeField()),
                ('judge', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'schoolapply',
                'verbose_name_plural': 'schoolapplies',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('school_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'get_latest_by': 'id',
            },
        ),
    ]
