# Generated by Django 2.2.5 on 2019-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'download_log',
                'verbose_name_plural': 'download_logs',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'program_like',
                'verbose_name_plural': 'program_likes',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.IntegerField()),
                ('code', models.TextField()),
                ('doc', models.TextField()),
                ('submit_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('judge', models.IntegerField()),
                ('judge_time', models.DateTimeField()),
                ('upload_time', models.DateTimeField()),
                ('downloads', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'get_latest_by': 'id',
            },
        ),
    ]
