# Generated by Django 2.2.5 on 2019-10-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(default='', max_length=64)),
                ('email_verify', models.CharField(default='', max_length=64)),
                ('realname', models.CharField(default='', max_length=32)),
                ('school', models.CharField(default='', max_length=64)),
                ('motto', models.CharField(default='', max_length=256)),
                ('permission', models.IntegerField(default=1)),
            ],
        ),
    ]
