# Generated by Django 2.2.5 on 2019-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64)),
                ('realname', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=64)),
                ('permission', models.IntegerField()),
            ],
        ),
    ]
