# Generated by Django 2.2.5 on 2019-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telphone',
            field=models.CharField(default=12345678900, max_length=11),
            preserve_default=False,
        ),
    ]
