# Generated by Django 2.2.5 on 2019-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_telphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('key', models.CharField(max_length=128)),
                ('deadtime', models.DateTimeField()),
            ],
        ),
    ]
