# Generated by Django 2.2.5 on 2019-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_entrylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
