# Generated by Django 2.2.5 on 2019-10-08 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20191008_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='entrytime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
