# Generated by Django 2.2.5 on 2019-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_entrylog_entrytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.CharField(default='', max_length=6),
        ),
    ]
