# Generated by Django 2.2.5 on 2019-10-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('quote', models.IntegerField()),
                ('send_time', models.DateTimeField()),
                ('read_time', models.DateTimeField()),
                ('valid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'mail',
                'verbose_name_plural': 'mails',
                'get_latest_by': 'id',
            },
        ),
    ]
